### PR TITLE
added modal

### PR DESCRIPTION
**Pull request by Esshahn**
adds a modal informing about the dataset being outdated and linking to kita navigator page.
modal can be closed and auto-closes on click outside of modal.

### CODE REVIEW

**Review by ff6347 — CHANGES_REQUESTED** [review]
@Esshahn Quick quick quick.

2 things

- Rounded corners seems odd for the application
- could the modal be in the center of the view. Currently it seems a little of. Or it could be a  part of the header?

**Comment by ff6347** [comment]
@Esshahn alternative start with the info tab expanded and add the message there

**Comment by ff6347** [comment]
Looks wired on mobile
image

**Comment by Esshahn** [comment]
agreed on the rounded corners. 
about the position, I found it a bit tricky to get it right as the content loads. I did not want it in the center but more as a note. I'll give it another shot later and try to not make it absolute position

**Pull request merged**
